[tool.poetry]
name = "real-estate-analysis"
version = "0.1.0"
description = "Analyzing Korean real-estate dynamically with public open data"
authors = ["Hyunsung Ro ", "DongHyun Kim <temeddix@gmail.com>"]
readme = "README.md"
packages = [{ include = "pages" }]

[tool.poetry.dependencies]
python = "^3.9.15"
streamlit = "1.25.0"
pydeck = "0.8.0"
watchdog = "3.0.0"
altair = "4.2.2"
pandas = "2.0.2"
numpy = "1.25.0"
aiohttp = "3.8.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
